language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t isurendra77/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true isurendra77/docker-react npm run test
